project_id = "rluhsstejgkghgheebgt"

[functions.extract-pdf]
verify_jwt = false

[functions.extract-image]
verify_jwt = false

[functions.convert-description]
verify_jwt = false

[functions.send-whatsapp]
verify_jwt = false

[functions.extract-fans]
verify_jwt = false

[functions.get-vapid-key]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.validate-team-code]
verify_jwt = false

[functions.get-team-jobs]
verify_jwt = false

[functions.update-team-job]
verify_jwt = false
